<?php

return [
    "management" => [
        "fullName" => "Management Team",
        "first" => "Management",
        "last" => "Team",
        "email" => "admin@retirementinsuranceoptions.com",
        "phone" => "1 (888) 601-3580",
        "bio" => "",
        "startedOn" => "",
        "role" => "Regional Management Team",
        "title" => "",
        "facebookUrl" => "https://facebook.com/americanseniorbenefitsSW",
        "linkedInUrl" => "",
        "qualifications" => "Management, Customer or Client Support"
    ],
    "dHavens" => [
        "fullName" => "Don Havens",
        "first" => "Don",
        "last" => "Havens",
        "email" => "donald.havens@gmail.com",
        "phone" => "1 (702) 529-4118",
        "bio" => "Don Havens Bio...",
        "startedOn" => "10-08-1985",
        "role" => "Regional Sales Manager",
        "title" => "RSM",
        "facebookUrl" => "",
        "linkedInUrl" => "",
        "qualifications" => "Management, Agent Resources"
    ],
    "jLawson" => [
        "fullName" => "Jennifer Lawson",
        "first" => "Jennifer",
        "last" => "Lawson",
        "email" => "admin@retirementinsuranceoptions.com",
        "phone" => "1 (702) 529-4410",
        "bio" => "Jennifer Lawson Bio...",
        "startedOn" => "11-02-2019",
        "role" => "Regional Administrator",
        "title" => "Admin",
        "facebookUrl" => "",
        "linkedInUrl" => "",
        "qualifications" => "Management, Customer Service, Agent Resources"
    ],
    "rSchlemmer" => [
        "fullName" => "Rich Schlemmer",
        "first" => "Rich",
        "last" => "Schlemmer",
        "email" => "rschlemm@gmail.com",
        "phone" => "1 (702) 326-2554",
        "bio" => "Rich Schlemmers Bio",
        "startedOn" => "?",
        "role" => "Certified Senior Advisor",
        "title" => "Agent",
        "facebookUrl" => "",
        "linkedInUrl" => "",
        "qualifications" => "Life, Medicare, Income Protection"
    ],
    "sBantz" => [
        "fullName" => "Shawn Bantz",
        "first" => "Shawn",
        "last" => "Bantz",
        "email" => "shawnbantz@gmail.com",
        "phone" => "1 (402) 217-2315",
        "bio" => "Shawn Bantz Bio",
        "startedOn" => "?",
        "role" => "Agent",
        "title" => "Agent",
        "facebookUrl" => "",
        "linkedInUrl" => "",
        "qualifications" => "Life, Medicare, Income Protection"
    ],
    "rAtkins" => [
        "fullName" => "Russel Atkins",
        "first" => "Russel",
        "last" => "Atkins",
        "email" => "russatkins25@gmail.com",
        "phone" => "1 (702) 325-8805",
        "bio" => "Russel Atkins Bio",
        "startedOn" => "?",
        "role" => "Agent",
        "title" => "Agent",
        "facebookUrl" => "",
        "linkedInUrl" => "",
        "qualifications" => "Life, Medicare, Income Protection"
    ],
    "sLange" => [
        "fullName" => "Shawn Lange",
        "first" => "Shawn",
        "last" => "Lange",
        "email" => "shawnlange76@gmail.com",
        "phone" => "1 (702) 339-6003",
        "bio" => "Shawn Lange Bio",
        "startedOn" => "?",
        "role" => "Agent",
        "title" => "Agent",
        "facebookUrl" => "",
        "linkedInUrl" => "",
        "qualifications" => "Life, Medicare, Income Protection"
    ],
    "rFink" => [
        "fullName" => "Rich Finkelstein",
        "first" => "Rich",
        "last" => "Finkelstein",
        "email" => "richfink@yahoo.com",
        "phone" => "1 (310) 938-5345",
        "bio" => "Rich Finkelstein Bio",
        "startedOn" => "?",
        "role" => "Financial Advisor",
        "title" => "Agent",
        "facebookUrl" => "",
        "linkedInUrl" => "",
        "qualifications" => "Life, Medicare, Financial Advisor"
    ],
    "mCrain" => [
        "fullName" => "Monica Crain",
        "first" => "Monica",
        "last" => "Crain",
        "email" => "monicaw880@gmail.com",
        "phone" => "1 (503) 753-8056",
        "bio" => "Monica Crain Bio",
        "startedOn" => "?",
        "role" => "Agent",
        "title" => "",
        "facebookUrl" => "",
        "linkedInUrl" => "",
        "qualifications" => "Life, Medicare, Income Protection"
    ],
    "rEdwards" => [
        "fullName" => "Richard Edwards",
        "first" => "Richard",
        "last" => "Edwards",
        "email" => "rck333@aol.com",
        "phone" => "1 (254)855-4238",
        "bio" => "Richard Edwards Bio",
        "startedOn" => "?",
        "role" => "Agent",
        "title" => "",
        "facebookUrl" => "",
        "linkedInUrl" => "",
        "qualifications" => "Life, Medicare, Income Protection"
    ]
];
